const GOAL = "Головна мета — не вивчити всі команди Windows, а навчитися швидко знаходити потрібну команду, розуміти її ризик і застосовувати її в реальному сценарії.";

const UK_HINTS = {
  "$PSVersionTable": "Версія PowerShell — перевір, що працюєш у PS 5 або 7.",
  "Get-Host": "Інформація про поточну оболонку (Name, Version).",
  "whoami": "Поточний користувач Windows.",
  "hostname": "Ім'я комп'ютера в мережі (DESKTOP-…).",
  "pwd": "Alias для Get-Location — поточна папка.",
  "Get-Location": "Повний шлях до поточної директорії.",
  "Get-Command git": "Чи встановлена команда git і де вона.",
  "Get-Command ssh": "Перевірка наявності OpenSSH client у Windows.",
  "Get-Command python": "Шлях до Python у $env:Path.",
  "echo $env:Path": "Список папок пошуку програм (PATH).",
  "$env:Path -split ';'": "PATH по одному шляху на рядок.",
  "Get-Help Get-ChildItem": "Довідка PowerShell для команди (cmdlet).",
  "ver": "Версія Windows (CMD).",
  "where git": "Де знаходиться git.exe (CMD).",
  "echo %PATH%": "PATH у CMD-синтаксисі.",
  "ls": "Alias → Get-ChildItem — список файлів.",
  "cd cli-test": "Alias → Set-Location — перехід у папку.",
  "mkdir cli-test": "Створює папку cli-test.",
  "New-Item notes.txt": "Створює новий файл або папку.",
  "Set-Content notes.txt \"Hello\"": "Записує текст у файл.",
  "Get-Content notes.txt": "Читає вміст файлу (alias: cat).",
  "Clear-Host": "Очищує екран (alias: cls).",
  "Get-History": "Історія команд PowerShell.",
  "dir": "CMD: список файлів (аналог ls).",
  "copy notes.txt backup.txt": "CMD: копіювання файлу.",
  "type notes.txt": "CMD: показати вміст файлу.",
  "del notes.txt": "CMD: видалити файл.",
  "tasklist": "CMD: список процесів.",
  "Copy-Item file.txt backup.txt": "Копіює файл або папку.",
  "Move-Item old.txt new.txt": "Переміщує/перейменовує.",
  "Remove-Item file.txt": "Видаляє файл.",
  "Remove-Item folder -Recurse -Force": "⚠ ВИСОКИЙ РИЗИК: рекурсивне примусове видалення!",
  "Rename-Item README.md NOTES.md": "Перейменовує файл.",
  "Get-ChildItem -Recurse -Filter \"*.md\"": "Рекурсивний пошук .md файлів.",
  "Select-String \"TODO\" -Path .\\* -Recurse": "Пошук тексту у файлах (аналог grep).",
  "findstr \"TODO\" *.md": "CMD: пошук тексту у файлах.",
  "ipconfig": "IP-адреса, gateway, DNS (PS і CMD).",
  "Get-NetIPConfiguration": "Детальна мережева конфігурація PowerShell.",
  "ping 8.8.8.8": "Перевірка доступності хоста.",
  "Test-NetConnection google.com -Port 443": "Перевірка TCP-порту (тут 443).",
  "Test-NetConnection 10.0.0.254 -Port 22": "Чи відкритий SSH на MikroTik (порт 22).",
  "tracert 8.8.8.8": "Маршрут пакетів до хоста.",
  "nslookup google.com": "DNS-запит.",
  "ssh Stas@10.0.0.254": "SSH до MikroTik роутера.",
  "ssh stanislav@raspberrypi.local": "SSH до Raspberry Pi.",
  "scp .\\backup.rsc Stas@10.0.0.254:": "Копіює файл на віддалений сервер.",
  "git status": "Стан Git-репозиторію.",
  "git clone https://github.com/user/project.git": "Клонує проєкт на диск.",
  "git pull": "Підтягує зміни з GitHub.",
  "gh auth status": "Статус GitHub CLI.",
  "python --version": "Версія Python на Windows.",
  "node --version": "Версія Node.js.",
  "winget search Git": "Пошук пакету в Windows Package Manager.",
  "winget install Git.Git": "Встановлює Git через winget.",
  "choco install git": "Встановлює через Chocolatey (якщо є).",
  "Get-Process": "Список запущених процесів.",
  "Stop-Process -Name notepad": "⚠ Завершує процес за іменем.",
  "Get-Service": "Список Windows-сервісів.",
  "Get-NetTCPConnection -State Listen": "Порти, що слухають з'єднання.",
  "netstat -ano": "CMD: мережеві з'єднання + PID.",
  "wsl --status": "Статус WSL на Windows.",
  "wsl --list --verbose": "Список дистрибутивів WSL.",
  "wsl": "Запускає default Linux (Ubuntu) у WSL.",
  "wsl -d Ubuntu": "Запуск конкретного дистрибутиву.",
  "iwr https://example.com/install.ps1 | iex": "⚠ Завантажує і виконує скрипт з інтернету!",
  "Set-ExecutionPolicy RemoteSigned": "⚠ Змінює політику виконання PS-скриптів."
};

function beginView(cmd) {
  viewChunks = [];
  if (cmd != null) viewChunks.push(`<div class="line-user">${esc(promptLabel.textContent)} ${esc(cmd)}</div>`);
}
function print(html, cls = "line-sys") { viewChunks.push(`<div class="${cls}">${html}</div>`); }
